version: '3.9'

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=factsdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
            timeout: 30s
            retries: 10
            interval: 3s
  app:
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
volumes:
  db-data: